services:
  test-mariadb:
    # https://hub.docker.com/_/mariadb
    image: docker.io/library/mariadb:12.0.2-noble
    environment:
      - MYSQL_DATABASE=mariadb
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    volumes:
      - test_mariadb_vol:/var/lib/mysql
    ports:
      - "127.0.0.1:3307:3306"

volumes:
  test_mariadb_vol: {}