name: ci

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  main:
    uses: jr200/github-action-templates/.github/workflows/ci_uv_python.yml@main
    with:
      run-tests: false
